### PR TITLE
refinements to Page + Section matching

### PR DESCRIPTION
**Pull request by Konfekt**
For example, pages can have numbers, and sections can have iterated +'s.

### CODE REVIEW

**Comment by lambdalisue** [comment]
Could you show me the working example? I don't really get it.

**Comment by Konfekt** [comment]
For example, now `K` on `pcre16(1)` or `grep(1+1)` works.

**Comment by lambdalisue** [comment]
> But I think it makes the code more fragile.

hum... what do you mean? I might miss something?

**Comment by Konfekt** [comment]
Because now one has to keep track that in the end `sect_pattern` is meant as `\v` expression, which is no longer clear from the outset. So the code is less readable in a way. But all fine,  your coding style prevails in your repo!

**Comment by lambdalisue** [comment]
> Because now one has to keep track that in the end sect_pattern is meant as \v expression, which is no longer clear from the outset. So the code is less readable in a way.

You are right in some point but I still think it is too redundant. That kind of coding rule may be required in some other plugins but this is quite small plugin thus I prefer my way.

> But all fine, your coding style prevails in your repo!

Thanks :-) Note that I still commented three points, in case you didn't notice.

**Comment by Konfekt** [comment]
Yeah I notice but somehow can't push anymore. Would you mind fixing?

**Comment by Konfekt** [comment]
Ok, pushed, but not sure if it's what you intended. If you could refine yourself after merging?

**Comment by lambdalisue** [comment]
it still have minor points but they are minor so it's ok. thanks a lot to follow my minor suggestions!

**Pull request merged**
